// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package quotesdispenser

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonF37e5e85DecodeGithubComSanyokbigQuotesServerInternalQuotesDispenser(in *jlexer.Lexer, out *Quotes) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		in.Skip()
		*out = nil
	} else {
		in.Delim('[')
		if *out == nil {
			if !in.IsDelim(']') {
				*out = make(Quotes, 0, 2)
			} else {
				*out = Quotes{}
			}
		} else {
			*out = (*out)[:0]
		}
		for !in.IsDelim(']') {
			var v1 Quote
			(v1).UnmarshalEasyJSON(in)
			*out = append(*out, v1)
			in.WantComma()
		}
		in.Delim(']')
	}
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonF37e5e85EncodeGithubComSanyokbigQuotesServerInternalQuotesDispenser(out *jwriter.Writer, in Quotes) {
	if in == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
		out.RawString("null")
	} else {
		out.RawByte('[')
		for v2, v3 := range in {
			if v2 > 0 {
				out.RawByte(',')
			}
			(v3).MarshalEasyJSON(out)
		}
		out.RawByte(']')
	}
}

// MarshalJSON supports json.Marshaler interface
func (v Quotes) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonF37e5e85EncodeGithubComSanyokbigQuotesServerInternalQuotesDispenser(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Quotes) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonF37e5e85EncodeGithubComSanyokbigQuotesServerInternalQuotesDispenser(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Quotes) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonF37e5e85DecodeGithubComSanyokbigQuotesServerInternalQuotesDispenser(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Quotes) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonF37e5e85DecodeGithubComSanyokbigQuotesServerInternalQuotesDispenser(l, v)
}
func easyjsonF37e5e85DecodeGithubComSanyokbigQuotesServerInternalQuotesDispenser1(in *jlexer.Lexer, out *Quote) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "quoteText":
			out.Text = string(in.String())
		case "quoteAuthor":
			out.Author = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonF37e5e85EncodeGithubComSanyokbigQuotesServerInternalQuotesDispenser1(out *jwriter.Writer, in Quote) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"quoteText\":"
		out.RawString(prefix[1:])
		out.String(string(in.Text))
	}
	{
		const prefix string = ",\"quoteAuthor\":"
		out.RawString(prefix)
		out.String(string(in.Author))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Quote) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonF37e5e85EncodeGithubComSanyokbigQuotesServerInternalQuotesDispenser1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Quote) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonF37e5e85EncodeGithubComSanyokbigQuotesServerInternalQuotesDispenser1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Quote) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonF37e5e85DecodeGithubComSanyokbigQuotesServerInternalQuotesDispenser1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Quote) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonF37e5e85DecodeGithubComSanyokbigQuotesServerInternalQuotesDispenser1(l, v)
}
